# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

requiredVersions:
    extensions:
        azure.ai.agents: '>=0.1.0-preview'
name: foundry-hosted-agent-quickstart
metadata:
    template: foundry-hosted-agent-quickstart
services:
    HostedAgent:
        project: ./src/HostedAgent
        host: azure.ai.agent
        language: dotnet
        docker:
            path: ./Dockerfile
            context: .
        config:
            container:
                resources:
                    cpu: "1"
                    memory: 2Gi
infra:
    provider: bicep
    path: ./infra
    module: main
pipeline:
    provider: github
    variables: []
    secrets: []
